server:
  port: 8080
  servlet:
    context-path: /x21a-api
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:h2:file:./data/x21aDB;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true


# UDA Logs
logging:
  level:
    root: INFO
    com.ejie.x21a: DEBUG
    com.ejie.x38: TRACE
